services:
  db:
    image: postgres:15
    container_name: mywallet-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: teste123
      POSTGRES_DB: mywallet
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d mywallet"]
      interval: 10s
      retries: 5

  app:
    image: mywallet-app:latest
    container_name: mywallet-app
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: prod  # Define o perfil como prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://db/mywallet
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: teste123
      SPRING_DATASOURCE_PLATFORM: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
      SPRING_JPA_SHOW_SQL: "false"
      SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
      SPRING_FLYWAY_LOCATIONS: classpath:db/migration
      SPRING_FLYWAY_ENABLED: "true"
      SERVER_PORT: 8082
    ports:
      - "8082:8082"

volumes:
  postgres_data:
